# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fa43d7f39ea7ef0425b4e72a7a2cd40fcfe7b19f623ece1504cd297d3daa25b94baaee174572b471a774096028ee09e7d0a9285ce4f536eafcc46e266d92b7cc

test:
  secret_key_base: 5594260998e2fdfb75230833a789a73c8fd7833b1d6696e08844d5a9b91aee2656941b845d7d545642ee1635a20666e0a010a7ea7d728434333a053bb537d37c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
